use crate::completion::{Namespace, Variable};
use crate::expression_parser::*;

#[derive(Debug, Clone)]
pub enum DataTypes {
    Unknown,
    Component,
    Destructible,
    Object,
    Mine,
    Controllable,
    Defensible,
    Container,
    Ship,
    Spacesuit,
    Station,
    Explosive,
    Bullet,
    Missile,
    Gate,
    Highwayentrygate,
    Highwayexitgate,
    Drop,
    Satellite,
    Navbeacon,
    Resourceprobe,
    Lockbox,
    Lock,
    Collectable,
    Collectableammo,
    Collectablewares,
    Buildstorage,
    Adsign,
    Shieldgenerator,
    Navcontext,
    Module,
    Buildmodule,
    Buildprocessor,
    Connectionmodule,
    Defencemodule,
    Ventureplatform,
    Habitationmodule,
    Pier,
    Production,
    Storagemodule,
    Engine,
    Scanner,
    Crate,
    Controlpanel,
    Signalleak,
    Room,
    Dockingbay,
    Walkablemodule,
    Dockarea,
    Space,
    Galaxy,
    Cluster,
    Sector,
    Zone,
    Highway,
    Region,
    Entity,
    Nonplayer,
    Npc,
    Weapon,
    Turret,
    Componentslot,
    Macroslot,
    Trade,
    Build,
    Operation,
    Licence,
    Group,
    Order,
    Constructionsequence,
    Constructionplanentryid,
    Constructionplanentrydata,
    Loadout,
    List,
    Table,
    String,
    Position,
    Vector,
    Rotation,
    Faction,
    Race,
    Ware,
    Lookuplist,
    Warelist,
    Wareamountlist,
    Cargolist,
    Npctemplate,
    Npctemplateentry,
    Macro,
    Unlock,
    Missiongroup,
    Notification,
    Tag,
    Cue,
    Enum,
    Kwenum,
    Dbdata,
    Class,
    Componentstate,
    Killmethod,
    Attention,
    Flightbehaviour,
    Flightcontrolmodel,
    Formationshape,
    Activity,
    Objective,
    Missiontype,
    Level,
    Alertlevel,
    Command,
    Commandaction,
    Cuestate,
    Dronemode,
    Roompopulationtype,
    Purpose,
    Moodlevel,
    Orderstate,
    Weaponmode,
    Dockstate,
    Quadrant,
    Datatype,
    Entitytype,
    Entityrole,
    Skilltype,
    Controlpost,
    Assignment,
    Controlposition,
    Unitcategory,
    Deployablecategory,
    Controlpaneltype,
    Signalleaktype,
    Roomtype,
    Boardingphase,
    Boardingbehaviour,
    Blacklisttype,
    Blacklistgroup,
    Waretransport,
    Relationchangereason,
    Shiptype,
    Numeric,
    Integer,
    Boolean,
    Money,
    Largeint,
    Float,
    Length,
    Angle,
    Hitpoints,
    Time,
    Largefloat,
}
impl Default for DataTypes {
    fn default() -> Self {
        DataTypes::Unknown
    }
}

#[derive(Debug, Clone)]
pub enum Keywords {
    Unknown,
    Player,
    Global,
    True,
    False,
    Pi,
    Null,
    Position,
    Vector,
    Rotation,
    Readtext,
    Stat,
    Userdata,
    Param,
    Loop,
    Datatype,
    Quadrant,
    Class,
    Componentstate,
    Ware,
    Warebasket,
    Waregroup,
    Unlock,
    Race,
    Faction,
    Macro,
    Tag,
    Lookup,
    Attention,
    Killmethod,
    Relationchangereason,
    Unitcategory,
    Deployablecategory,
    Command,
    Commandaction,
    Activity,
    Entitytype,
    Entityrole,
    Skilltype,
    Controlpost,
    Assignment,
    Controlposition,
    Formationshape,
    Level,
    Alertlevel,
    Roompopulationtype,
    Purpose,
    Controlpaneltype,
    Signalleaktype,
    Boardingphase,
    Boardingbehaviour,
    Blacklisttype,
    Blacklistgroup,
    Waretransport,
    Orderstate,
    Moodlevel,
    Weaponmode,
    Dronemode,
    Dockstate,
    Shiptype,
    Roomtype,
    Notification,
    Flightbehaviour,
    Flightcontrolmodel,
    Objective,
    Missiontype,
    Missiongroup,
    Cuestate,
    This,
    Event,
    Quota,
    Md,
    Parent,
    Static,
    Staticbase,
    Namespace,
}
impl Default for Keywords {
    fn default() -> Self {
        Keywords::Unknown
    }
}

pub fn update_types(
    namespace: &std::collections::HashMap<&str, Variable<'_>>,
    datatype: Vec<DataTypes>,
) -> Vec<DataTypes> {
    datatype
}

pub fn infer_types(token: &Token) -> Option<Vec<DataTypes>> {
    None
}

pub fn match_keyword(string: &str) -> Keywords {
    match string {
        "player" => Keywords::Player,
        "global" => Keywords::Global,
        "true" => Keywords::True,
        "false" => Keywords::False,
        "pi" => Keywords::Pi,
        "null" => Keywords::Null,
        "position" => Keywords::Position,
        "vector" => Keywords::Vector,
        "rotation" => Keywords::Rotation,
        "readtext" => Keywords::Readtext,
        "stat" => Keywords::Stat,
        "userdata" => Keywords::Userdata,
        "param" => Keywords::Param,
        "loop" => Keywords::Loop,
        "datatype" => Keywords::Datatype,
        "quadrant" => Keywords::Quadrant,
        "class" => Keywords::Class,
        "componentstate" => Keywords::Componentstate,
        "ware" => Keywords::Ware,
        "warebasket" => Keywords::Warebasket,
        "waregroup" => Keywords::Waregroup,
        "unlock" => Keywords::Unlock,
        "race" => Keywords::Race,
        "faction" => Keywords::Faction,
        "macro" => Keywords::Macro,
        "tag" => Keywords::Tag,
        "lookup" => Keywords::Lookup,
        "attention" => Keywords::Attention,
        "killmethod" => Keywords::Killmethod,
        "relationchangereason" => Keywords::Relationchangereason,
        "unitcategory" => Keywords::Unitcategory,
        "deployablecategory" => Keywords::Deployablecategory,
        "command" => Keywords::Command,
        "commandaction" => Keywords::Commandaction,
        "activity" => Keywords::Activity,
        "entitytype" => Keywords::Entitytype,
        "entityrole" => Keywords::Entityrole,
        "skilltype" => Keywords::Skilltype,
        "controlpost" => Keywords::Controlpost,
        "assignment" => Keywords::Assignment,
        "controlposition" => Keywords::Controlposition,
        "formationshape" => Keywords::Formationshape,
        "level" => Keywords::Level,
        "alertlevel" => Keywords::Alertlevel,
        "roompopulationtype" => Keywords::Roompopulationtype,
        "purpose" => Keywords::Purpose,
        "controlpaneltype" => Keywords::Controlpaneltype,
        "signalleaktype" => Keywords::Signalleaktype,
        "boardingphase" => Keywords::Boardingphase,
        "boardingbehaviour" => Keywords::Boardingbehaviour,
        "blacklisttype" => Keywords::Blacklisttype,
        "blacklistgroup" => Keywords::Blacklistgroup,
        "waretransport" => Keywords::Waretransport,
        "orderstate" => Keywords::Orderstate,
        "moodlevel" => Keywords::Moodlevel,
        "weaponmode" => Keywords::Weaponmode,
        "dronemode" => Keywords::Dronemode,
        "dockstate" => Keywords::Dockstate,
        "shiptype" => Keywords::Shiptype,
        "roomtype" => Keywords::Roomtype,
        "notification" => Keywords::Notification,
        "flightbehaviour" => Keywords::Flightbehaviour,
        "flightcontrolmodel" => Keywords::Flightcontrolmodel,
        "objective" => Keywords::Objective,
        "missiontype" => Keywords::Missiontype,
        "missiongroup" => Keywords::Missiongroup,
        "cuestate" => Keywords::Cuestate,
        "this" => Keywords::This,
        "event" => Keywords::Event,
        "quota" => Keywords::Quota,
        "md" => Keywords::Md,
        "parent" => Keywords::Parent,
        "static" => Keywords::Static,
        "staticbase" => Keywords::Staticbase,
        "namespace" => Keywords::Namespace,
        _ => Keywords::Unknown,
    }
}

pub fn match_datatypes(string: &str) -> DataTypes {
    match string {
        "component" => DataTypes::Component,
        "destructible" => DataTypes::Destructible,
        "object" => DataTypes::Object,
        "mine" => DataTypes::Mine,
        "controllable" => DataTypes::Controllable,
        "defensible" => DataTypes::Defensible,
        "container" => DataTypes::Container,
        "ship" => DataTypes::Ship,
        "spacesuit" => DataTypes::Spacesuit,
        "station" => DataTypes::Station,
        "explosive" => DataTypes::Explosive,
        "bullet" => DataTypes::Bullet,
        "missile" => DataTypes::Missile,
        "gate" => DataTypes::Gate,
        "highwayentrygate" => DataTypes::Highwayentrygate,
        "highwayexitgate" => DataTypes::Highwayexitgate,
        "drop" => DataTypes::Drop,
        "satellite" => DataTypes::Satellite,
        "navbeacon" => DataTypes::Navbeacon,
        "resourceprobe" => DataTypes::Resourceprobe,
        "lockbox" => DataTypes::Lockbox,
        "lock" => DataTypes::Lock,
        "collectable" => DataTypes::Collectable,
        "collectableammo" => DataTypes::Collectableammo,
        "collectablewares" => DataTypes::Collectablewares,
        "buildstorage" => DataTypes::Buildstorage,
        "adsign" => DataTypes::Adsign,
        "shieldgenerator" => DataTypes::Shieldgenerator,
        "navcontext" => DataTypes::Navcontext,
        "module" => DataTypes::Module,
        "buildmodule" => DataTypes::Buildmodule,
        "buildprocessor" => DataTypes::Buildprocessor,
        "connectionmodule" => DataTypes::Connectionmodule,
        "defencemodule" => DataTypes::Defencemodule,
        "ventureplatform" => DataTypes::Ventureplatform,
        "habitationmodule" => DataTypes::Habitationmodule,
        "pier" => DataTypes::Pier,
        "production" => DataTypes::Production,
        "storagemodule" => DataTypes::Storagemodule,
        "engine" => DataTypes::Engine,
        "scanner" => DataTypes::Scanner,
        "crate" => DataTypes::Crate,
        "controlpanel" => DataTypes::Controlpanel,
        "signalleak" => DataTypes::Signalleak,
        "room" => DataTypes::Room,
        "dockingbay" => DataTypes::Dockingbay,
        "walkablemodule" => DataTypes::Walkablemodule,
        "dockarea" => DataTypes::Dockarea,
        "space" => DataTypes::Space,
        "galaxy" => DataTypes::Galaxy,
        "cluster" => DataTypes::Cluster,
        "sector" => DataTypes::Sector,
        "zone" => DataTypes::Zone,
        "highway" => DataTypes::Highway,
        "region" => DataTypes::Region,
        "entity" => DataTypes::Entity,
        "nonplayer" => DataTypes::Nonplayer,
        "npc" => DataTypes::Npc,
        "weapon" => DataTypes::Weapon,
        "turret" => DataTypes::Turret,
        "componentslot" => DataTypes::Componentslot,
        "macroslot" => DataTypes::Macroslot,
        "trade" => DataTypes::Trade,
        "build" => DataTypes::Build,
        "operation" => DataTypes::Operation,
        "licence" => DataTypes::Licence,
        "group" => DataTypes::Group,
        "order" => DataTypes::Order,
        "constructionsequence" => DataTypes::Constructionsequence,
        "constructionplanentryid" => DataTypes::Constructionplanentryid,
        "constructionplanentrydata" => DataTypes::Constructionplanentrydata,
        "loadout" => DataTypes::Loadout,
        "list" => DataTypes::List,
        "table" => DataTypes::Table,
        "string" => DataTypes::String,
        "position" => DataTypes::Position,
        "vector" => DataTypes::Vector,
        "rotation" => DataTypes::Rotation,
        "faction" => DataTypes::Faction,
        "race" => DataTypes::Race,
        "ware" => DataTypes::Ware,
        "lookuplist" => DataTypes::Lookuplist,
        "warelist" => DataTypes::Warelist,
        "wareamountlist" => DataTypes::Wareamountlist,
        "cargolist" => DataTypes::Cargolist,
        "npctemplate" => DataTypes::Npctemplate,
        "npctemplateentry" => DataTypes::Npctemplateentry,
        "macro" => DataTypes::Macro,
        "unlock" => DataTypes::Unlock,
        "missiongroup" => DataTypes::Missiongroup,
        "notification" => DataTypes::Notification,
        "tag" => DataTypes::Tag,
        "cue" => DataTypes::Cue,
        "enum" => DataTypes::Enum,
        "kwenum" => DataTypes::Kwenum,
        "dbdata" => DataTypes::Dbdata,
        "class" => DataTypes::Class,
        "componentstate" => DataTypes::Componentstate,
        "killmethod" => DataTypes::Killmethod,
        "attention" => DataTypes::Attention,
        "flightbehaviour" => DataTypes::Flightbehaviour,
        "flightcontrolmodel" => DataTypes::Flightcontrolmodel,
        "formationshape" => DataTypes::Formationshape,
        "activity" => DataTypes::Activity,
        "objective" => DataTypes::Objective,
        "missiontype" => DataTypes::Missiontype,
        "level" => DataTypes::Level,
        "alertlevel" => DataTypes::Alertlevel,
        "command" => DataTypes::Command,
        "commandaction" => DataTypes::Commandaction,
        "cuestate" => DataTypes::Cuestate,
        "dronemode" => DataTypes::Dronemode,
        "roompopulationtype" => DataTypes::Roompopulationtype,
        "purpose" => DataTypes::Purpose,
        "moodlevel" => DataTypes::Moodlevel,
        "orderstate" => DataTypes::Orderstate,
        "weaponmode" => DataTypes::Weaponmode,
        "dockstate" => DataTypes::Dockstate,
        "quadrant" => DataTypes::Quadrant,
        "datatype" => DataTypes::Datatype,
        "entitytype" => DataTypes::Entitytype,
        "entityrole" => DataTypes::Entityrole,
        "skilltype" => DataTypes::Skilltype,
        "controlpost" => DataTypes::Controlpost,
        "assignment" => DataTypes::Assignment,
        "controlposition" => DataTypes::Controlposition,
        "unitcategory" => DataTypes::Unitcategory,
        "deployablecategory" => DataTypes::Deployablecategory,
        "controlpaneltype" => DataTypes::Controlpaneltype,
        "signalleaktype" => DataTypes::Signalleaktype,
        "roomtype" => DataTypes::Roomtype,
        "boardingphase" => DataTypes::Boardingphase,
        "boardingbehaviour" => DataTypes::Boardingbehaviour,
        "blacklisttype" => DataTypes::Blacklisttype,
        "blacklistgroup" => DataTypes::Blacklistgroup,
        "waretransport" => DataTypes::Waretransport,
        "relationchangereason" => DataTypes::Relationchangereason,
        "shiptype" => DataTypes::Shiptype,
        "numeric" => DataTypes::Numeric,
        "integer" => DataTypes::Integer,
        "boolean" => DataTypes::Boolean,
        "money" => DataTypes::Money,
        "largeint" => DataTypes::Largeint,
        "float" => DataTypes::Float,
        "length" => DataTypes::Length,
        "angle" => DataTypes::Angle,
        "hitpoints" => DataTypes::Hitpoints,
        "time" => DataTypes::Time,
        "largefloat" => DataTypes::Largefloat,
        _ => DataTypes::Unknown,
    }
}
